### ISSUE TITLE
How to support this project

### ISSUE THREAD

**Issue by isaaclyman** [obadakhalili/Sprightly#12]
Hi, I've been using Sprightly since 2022 and have found it very useful. Thank you for building it.

I have two questions:

- What is the license for this project?
- Is there a way I can donate to support your open-source work?

**Comment by obadakhalili** [comment]
- I'm overwhelmed that you are using my project and finding it useful. No need for donations, you can support me by giving me feedback on how to improve the project!
- I just MIT-licensed the project. Do you have other suggestions?

**Comment by isaaclyman** [comment]
I honestly have no suggestions. Sprightly is perfect for my use case because it's small, simple, and doesn't need much setup or configuration.

Thank you for MIT-licensing, that's great.

Are you sure you won't accept a donation? I could also donate to a charitable organization on your behalf, if you prefer. I feel it's important to show support for the open source projects that have improved my life.

**Comment by obadakhalili** [comment]
Thank you for reminding me about licensing! I'm surprised I haven't already. If you would like to donate, consider contributing to [UNICEF's campaign](https://www.unicef.org/emergencies/children-gaza-need-lifesaving-support) for children of Gaza, it would mean a lot.

Thanks in advance, @isaaclyman.

**Comment by isaaclyman** [comment]
<img width="969" alt="Screenshot 2024-12-06 at 8 50 19 AM" src="https://github.com/user-attachments/assets/04c95801-0fb4-4dda-a18c-017c7d143319">

Done! Thank you again.

**Comment by obadakhalili** [comment]
This was wholesome. Thanks a lot, @isaaclyman, this means a lot to me!
