### ISSUE TITLE
Rewrite Sprightly's engine

### ISSUE THREAD

**Issue by obadakhalili** [obadakhalili/sprightly#2]
Make sure that the rewrite achieves the following:
* The engine should be written in TS.
* Follow a functional approach to implement the engine, as opposed to the OOP one implemented currently.
* Use JS's new method `.replaceAll()` to implement the transformation logic.
* Currently, if you have the views directory set to `./views` and the dir is laid out as follows:
```
./views
+- file.spy
+- subfolder
+---- nested-file.spy
```
If `subfolder/nested-file.spy` wanted to include `file.spy` as a partial, it would have to reference it as follows `./file.spy` instead of `../file.spy` (since it's one level up in the tree) because the files are resolved relative to the pre-set `./views` directory. You need to fix this behavior and implement the correct one mentioned first.
* Implement a good error tracing strategy.
* Implement a caching strategy.
* Support escaping syntax.
* The API should take the form:
```.ts
function sprightly(
  entryPoint: string,
  data: Record<string, string>,
  options: { cache: boolean }
): Promise<string> {
  ...
}
```
* Support accessing nested properties. Example:
Given
```html
<h1>{{ nested.property }}</h1>
```
and
```js
const data = {
  nested: {
    property: "Osid's awesome"
  }
}
```
should resolve in:
```html
<h1>Osid's awesome</h1>
```
* Support express through the `.__express` property. Read more [here](https://expressjs.com/en/4x/api.html#app.engine) and [here](https://github.com/expressjs/express/blob/master/lib/application.js#L267-L286).

**Comment by obadakhalili** [comment]
These are the change in requirements after writing the initial tests:
* There's a `keyFallback` option that is used as follows:
  * If a referenced key is not found in the data object and `keyFallback` is not set, then the resolved value should be an empty string.
  * If a referenced key is not found in the data object and `keyFallback` is set, then the resolved value should be the value assigned to the option.
 * There's a `throwOnKeyNotfound` that does the following: If a referenced key is not found in the data object and this option is enabled, then the engine should throw a [custom error](https://javascript.info/custom-errors) containing a string with tracing info (can be used to render in express).
 * We need to support array indexing syntax as well. So this syntax for example is supported:
 ```js
const data = {
  property: {
    nested: [{ anotherProperty: ["foo", "bar"] }]
  }
}

// in template
property.nested[0].anotherProperty[1] // results in "bar"
 ```
* If the entry point isn't found, it throws an error containing that.
* If a referenced component isn't found, it throws an error containing tracing info for that.
* I will comment the specific requirements for supporting escaping later when I know them 😃.

@OsidAbu-alrub.

**Comment by OsidAbu-alrub** [comment]
What can cause errors in the application? Missing components or wrong file paths for example?
